- name: restart nginx
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: restart haproxy_rsyslog
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - haproxy
    - rsyslog

